apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T17:48:06Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4358"
  uid: ec99d832-2f8d-436b-9b1e-c540f41b344a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.45.140
  clusterIPs:
  - 10.104.45.140
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31419
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
